### ISSUE TITLE
When i run the compiler it gives me an error

### ISSUE THREAD

**Issue by Colean128** [tobes898/SeniorProject17#1]
I was making a simple InSpace program that would print out "Hello World" and stop.
When trying to compile it I get this error.
`Syntax Error: Missing Token at line 1  
Syntax Check Failed!
`
Can you help me?
-Zayne, creator of InSpace

**Comment by ripark** [comment]
Any chance you're missing a ; at the end of the line? tobes wrote the compiler to require a ; to terminate each line. I'm trying to think of other issues that might cause the syntax error on line 1, but tobes may have more answers.

**Comment by tobyduncan** [comment]
I agree that it sounds like you are missing a ; at the end of the line. Do you happen to have the source code for what you are trying to compile?

**Comment by tobyduncan** [comment]
Closing the issue due to no response. I think you may have been using an older version of the compiler as well. I have since updated the repository with the most up-to-date version in the folder current_version
